# Generated by Django 5.1.7 on 2025-04-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Article image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('categories', models.ManyToManyField(related_name='articles', to='healthtips_new.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
