# Generated by Django 5.2 on 2025-04-09 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Hospital Name')),
                ('address', models.TextField(verbose_name='Hospital Address')),
                ('working_time', models.CharField(max_length=50, verbose_name='Working Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название анализа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='Число отзывов')),
                ('reviews_data', models.JSONField(blank=True, null=True, verbose_name='Детальные отзывы')),
                ('category', models.CharField(max_length=150, verbose_name='Категория анализа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('ready', models.CharField(choices=[('Within 1 day', 'Within 1 day'), ('1-3 days', '1-3 days'), ('More than 3 days', 'More than 3 days')], default='1-3 days', max_length=30, verbose_name='Время готовности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='analysis.hospital', verbose_name='Лаборатория (из Hospital)')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysis')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
