# Generated by Django 5.1.5 on 2025-04-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_hospitalreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время приёма'),
        ),
    ]
