# Generated by Django 5.1.7 on 2025-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_testrecord_created_at_alter_testrecord_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='abouttest',
            field=models.TextField(blank=True, null=True, verbose_name='О тесте'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='preparation',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкция по подготовке'),
        ),
    ]
