# Generated by Django 5.1.7 on 2025-05-07 13:01

import checkAI.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkAI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkaichat',
            name='secret_token',
            field=models.CharField(blank=True, default=checkAI.models.generate_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='checkaichat',
            name='title',
            field=models.CharField(default='New Chat', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkaichat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkai_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
