# Generated by Django 5.1.7 on 2025-05-07 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkAI', '0002_checkaichat_secret_token_alter_checkaichat_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkaimessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='checkaichat',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkaichat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkaichat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkai_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
