# Generated by Django 5.1.5 on 2025-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_analysis_paymentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время приёма'),
        ),
    ]
