# Generated by Django 5.1.7 on 2025-05-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
