# Generated by Django 5.1.7 on 2025-05-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationhistory_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='type',
            field=models.CharField(choices=[('test_reminder', 'Test Reminder'), ('result_alert', 'Result Alert'), ('appointment', 'Appointment Confirmation')], default='test_reminder', max_length=32),
        ),
    ]
