# Generated by Django 5.1.7 on 2025-05-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationhistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='email_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='type',
            field=models.CharField(choices=[('test_reminder', 'Test Reminder'), ('result_alert', 'Result Alert'), ('appointment', 'Appointment Confirmation'), ('result_rejected', 'Result Rejected')], default='test_reminder', max_length=32),
        ),
    ]
